version: 2.1

orbs:
  docker: circleci/docker@1.5.0

executors:
  docker-publisher:
    environment:
      DOCKER_IMAGE_NAME: docker.io/altafmansuri/thor_frontend
    docker:
      - image: cimg/node:18.17.0  # Updated image with Angular compatibility
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  build-angular:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Angular CLI
          command: npm install -g @angular/cli
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Angular app
          command: ng build --configuration=production
      - run:
          name: Docker login
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_IMAGE_NAME .
      - run:
          name: Push Docker image
          command: docker push $DOCKER_IMAGE_NAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-angular