version: 2.1

orbs:
  docker: circleci/docker@1.5.0

executors:
  docker-publisher:
    environment:
      Thor_frontend: docker.io/altafmansuri/thor_frontend
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  publishFlaskAndExpress:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - publishFlaskAndExpress